name: Fuck Location CI Build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - id: get-project
        name: Get project FuckLocation
        run: echo "::set-output name=PROJECT::$(cat project-to-build)"
      - name: Clone project
        run: git clone --depth=1 ${{ steps.get-project.outputs.PROJECT }} https://github.com/Mikotwa/FuckLocation.git
      - name: Build the app
        working-directory: ./FuckLocation
        run: |
          if [ ! -f "gradlew" ]; then gradle wrapper; fi
          chmod +x gradlew
          ./gradlew assembleDebug --stacktrace
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug.apk
          path: ./**/*.apk
      - name: Send notifications
        if: cancelled() == false
        uses: xinthink/action-telegram@v1.1
        with:
          chatId: ${{ secrets.TELEGRAM_ID_OR_CHANNEL }}
          botToken: ${{ secrets.TELEGRAM_TOKEN }}
          jobStatus: ${{ job.status }}
          skipSuccess: false